import { HTTP_METHODS } from "../types";
import type { AuthType, BodyMode, HttpMethod } from "../types";

export interface ParsedCurlRequest {
  method: HttpMethod;
  /** Base URL with the query string stripped out — the query string becomes `queryParams` instead, matching how Postman splits a pasted URL. */
  url: string;
  queryParams: [string, string][];
  /** Excludes the Authorization header when it was recognized as Basic/Bearer and pulled into `authType`/`authConfig` instead. */
  headers: [string, string][];
  bodyMode: BodyMode;
  jsonBody: string;
  rawBody: string;
  formData: [string, string][];
  authType: AuthType;
  /** Shape matches the single auth type's config (e.g. `{ username, password }` for basic) — same convention `authConfigFromSavedRequest` already expects. */
  authConfig: unknown;
}

export type ParseCurlResult = { ok: true; result: ParsedCurlRequest } | { ok: false; error: string };

/**
 * Splits a shell command string into argv-style tokens, understanding single
 * quotes (literal, no escapes), double quotes (backslash-escapes `"`, `\`,
 * `$`), and backslash-escaping outside quotes. This covers how curl commands
 * are actually generated by browsers' "Copy as cURL" and by users pasting
 * from a terminal — a full POSIX shell grammar isn't needed for that.
 */
function tokenize(command: string): string[] {
  const tokens: string[] = [];
  let i = 0;
  const n = command.length;

  while (i < n) {
    while (i < n && /\s/.test(command[i])) i++;
    if (i >= n) break;

    let token = "";
    while (i < n && !/\s/.test(command[i])) {
      const ch = command[i];
      if (ch === "'") {
        i++;
        while (i < n && command[i] !== "'") {
          token += command[i];
          i++;
        }
        i++; // closing quote
      } else if (ch === '"') {
        i++;
        while (i < n && command[i] !== '"') {
          if (command[i] === "\\" && i + 1 < n && '"\\$`'.includes(command[i + 1])) {
            token += command[i + 1];
            i += 2;
          } else {
            token += command[i];
            i++;
          }
        }
        i++; // closing quote
      } else if (ch === "\\" && i + 1 < n) {
        token += command[i + 1];
        i += 2;
      } else {
        token += ch;
        i++;
      }
    }
    tokens.push(token);
  }

  return tokens;
}

// Flags that take a following value. Ones we don't otherwise act on (e.g.
// --connect-timeout) are still listed here so their value isn't mistaken for
// the URL or another flag.
const HEADER_FLAGS = new Set(["--header", "-H"]);
const METHOD_FLAGS = new Set(["--request", "-X"]);
const DATA_FLAGS = new Set(["--data", "--data-raw", "--data-binary", "--data-ascii", "-d"]);
const FORM_FLAGS = new Set(["--form", "-F"]);
const USER_FLAGS = new Set(["--user", "-u"]);
const URL_FLAGS = new Set(["--url"]);
const USER_AGENT_FLAGS = new Set(["--user-agent", "-A"]);
const REFERER_FLAGS = new Set(["--referer", "-e"]);
const COOKIE_FLAGS = new Set(["--cookie", "-b"]);
const IGNORED_VALUE_FLAGS = new Set([
  "--connect-timeout",
  "--max-time",
  "-o",
  "--output",
  "--proxy",
  "-x",
  "--cacert",
  "--cert",
  "-E",
  "--key",
  "--data-urlencode",
]);
const VALUE_FLAGS = new Set([
  ...HEADER_FLAGS,
  ...METHOD_FLAGS,
  ...DATA_FLAGS,
  ...FORM_FLAGS,
  ...USER_FLAGS,
  ...URL_FLAGS,
  ...USER_AGENT_FLAGS,
  ...REFERER_FLAGS,
  ...COOKIE_FLAGS,
  ...IGNORED_VALUE_FLAGS,
]);

function isHttpMethod(value: string): value is HttpMethod {
  return (HTTP_METHODS as readonly string[]).includes(value.toUpperCase());
}

function findHeader(headers: [string, string][], name: string): string | undefined {
  return headers.find(([key]) => key.toLowerCase() === name.toLowerCase())?.[1];
}

/** Splits a URL into its base (scheme+host+path) and query-param pairs, tolerating a URL that isn't a fully valid absolute URL yet (e.g. it still contains a `{{baseUrl}}` template). */
function splitUrl(rawUrl: string): { base: string; queryParams: [string, string][] } {
  try {
    const url = new URL(rawUrl);
    const queryParams = Array.from(url.searchParams.entries());
    return { base: `${url.origin}${url.pathname}`, queryParams };
  } catch {
    const [base, query] = rawUrl.split("?");
    const queryParams = query ? Array.from(new URLSearchParams(query).entries()) : [];
    return { base, queryParams };
  }
}

/** Decodes a Basic-auth header value ("Basic <base64>") into `{ username, password }`, or `null` if it isn't valid Basic auth. */
function decodeBasicAuth(headerValue: string): { username: string; password: string } | null {
  const match = /^basic\s+(\S+)$/i.exec(headerValue.trim());
  if (!match) return null;
  try {
    const decoded = atob(match[1]);
    const separatorIndex = decoded.indexOf(":");
    if (separatorIndex === -1) return null;
    return { username: decoded.slice(0, separatorIndex), password: decoded.slice(separatorIndex + 1) };
  } catch {
    return null;
  }
}

function decodeBearerAuth(headerValue: string): { token: string } | null {
  const match = /^bearer\s+(\S+)$/i.exec(headerValue.trim());
  return match ? { token: match[1] } : null;
}

function detectBodyMode(data: string, contentType: string | undefined): BodyMode {
  if (contentType) {
    const normalized = contentType.toLowerCase();
    if (normalized.includes("application/json")) return "json";
    if (normalized.includes("application/x-www-form-urlencoded")) return "form-data";
    return "raw";
  }
  try {
    JSON.parse(data);
    return "json";
  } catch {
    // not JSON — fall through to the form-urlencoded heuristic below
  }
  const looksFormEncoded = /^[^\s{}[\]]+=[^\s]*(&[^\s{}[\]]+=[^\s]*)*$/.test(data);
  return looksFormEncoded ? "form-data" : "raw";
}

/**
 * Parses a `curl` command (as pasted from a terminal, or generated by a
 * browser's "Copy as cURL") into the fields the request builder's draft
 * needs. Recognizes `--location`/`-X`/`--header`/`--data*`/`--form`/`--user`/
 * `--url` plus a handful of header-shorthand flags; unrecognized flags are
 * skipped (with their value, if any) rather than causing a parse failure, so
 * an unusual flag doesn't block the rest of the import.
 */
export function parseCurlCommand(input: string): ParseCurlResult {
  const trimmed = input.trim();
  if (trimmed === "") return { ok: false, error: "Paste a curl command to import." };

  // Join backslash line-continuations before tokenizing.
  const joined = trimmed.replace(/\\\r?\n/g, " ");
  const tokens = tokenize(joined);
  const startIndex = tokens[0]?.toLowerCase() === "curl" ? 1 : 0;

  let url: string | null = null;
  let explicitMethod: HttpMethod | null = null;
  let impliedMethod: HttpMethod = "GET";
  const headers: [string, string][] = [];
  const dataParts: string[] = [];
  const formParts: [string, string][] = [];
  let basicAuthFromUserFlag: { username: string; password: string } | null = null;

  for (let i = startIndex; i < tokens.length; i++) {
    const token = tokens[i];

    if (METHOD_FLAGS.has(token)) {
      const value = tokens[++i];
      if (value && isHttpMethod(value)) explicitMethod = value.toUpperCase() as HttpMethod;
      continue;
    }
    if (HEADER_FLAGS.has(token)) {
      const value = tokens[++i] ?? "";
      const separatorIndex = value.indexOf(":");
      if (separatorIndex !== -1) {
        headers.push([value.slice(0, separatorIndex).trim(), value.slice(separatorIndex + 1).trim()]);
      }
      continue;
    }
    if (DATA_FLAGS.has(token)) {
      dataParts.push(tokens[++i] ?? "");
      impliedMethod = "POST";
      continue;
    }
    if (FORM_FLAGS.has(token)) {
      const value = tokens[++i] ?? "";
      const separatorIndex = value.indexOf("=");
      if (separatorIndex !== -1) formParts.push([value.slice(0, separatorIndex), value.slice(separatorIndex + 1)]);
      impliedMethod = "POST";
      continue;
    }
    if (USER_FLAGS.has(token)) {
      const value = tokens[++i] ?? "";
      const separatorIndex = value.indexOf(":");
      basicAuthFromUserFlag =
        separatorIndex === -1
          ? { username: value, password: "" }
          : { username: value.slice(0, separatorIndex), password: value.slice(separatorIndex + 1) };
      continue;
    }
    if (USER_AGENT_FLAGS.has(token)) {
      headers.push(["User-Agent", tokens[++i] ?? ""]);
      continue;
    }
    if (REFERER_FLAGS.has(token)) {
      headers.push(["Referer", tokens[++i] ?? ""]);
      continue;
    }
    if (COOKIE_FLAGS.has(token)) {
      headers.push(["Cookie", tokens[++i] ?? ""]);
      continue;
    }
    if (URL_FLAGS.has(token)) {
      url = tokens[++i] ?? null;
      continue;
    }
    if (IGNORED_VALUE_FLAGS.has(token)) {
      i++; // skip the value, we don't model this option
      continue;
    }
    if (VALUE_FLAGS.has(token)) {
      i++; // defensive: any other listed value-flag we didn't special-case above
      continue;
    }
    if (token.startsWith("-")) {
      continue; // a boolean flag we don't model (--location, --compressed, -k, -v, -s, ...)
    }
    if (url === null) {
      url = token; // the first bare argument is the URL
    }
  }

  if (!url) return { ok: false, error: "Couldn't find a URL in that curl command." };

  const { base, queryParams } = splitUrl(url);
  const method = explicitMethod ?? impliedMethod;

  let authType: AuthType = "none";
  let authConfig: unknown;
  const authHeaderValue = findHeader(headers, "Authorization");
  if (authHeaderValue) {
    const basic = decodeBasicAuth(authHeaderValue);
    const bearer = basic ? null : decodeBearerAuth(authHeaderValue);
    if (basic) {
      authType = "basic";
      authConfig = basic;
    } else if (bearer) {
      authType = "bearer";
      authConfig = bearer;
    }
    // An Authorization header we recognized is represented via the Auth tab
    // instead of staying in the headers list.
    if (basic || bearer) {
      const index = headers.findIndex(([key]) => key.toLowerCase() === "authorization");
      if (index !== -1) headers.splice(index, 1);
    }
  } else if (basicAuthFromUserFlag) {
    authType = "basic";
    authConfig = basicAuthFromUserFlag;
  }

  const data = dataParts.join("&");
  let bodyMode: BodyMode = "none";
  let jsonBody = "";
  let rawBody = "";
  let formData: [string, string][] = [];

  if (data !== "") {
    bodyMode = detectBodyMode(data, findHeader(headers, "Content-Type"));
    if (bodyMode === "json") {
      try {
        jsonBody = JSON.stringify(JSON.parse(data), null, 2);
      } catch {
        jsonBody = data;
      }
    } else if (bodyMode === "form-data") {
      formData = Array.from(new URLSearchParams(data).entries());
    } else {
      rawBody = data;
    }
  } else if (formParts.length > 0) {
    bodyMode = "form-data";
    formData = formParts;
  }

  return {
    ok: true,
    result: { method, url: base, queryParams, headers, bodyMode, jsonBody, rawBody, formData, authType, authConfig },
  };
}
